# Generated by Django 5.1.4 on 2025-01-07 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSet',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created_users', models.ManyToManyField(related_name='tasks_created_by_u', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('github', 'Github'), ('file', 'File'), ('text', 'Text')], max_length=256)),
                ('github_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('codeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_attached_to_c', to='main.codeset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
