# Generated by Django 5.1.4 on 2025-01-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='file',
            name='text',
            field=models.TextField(blank=True, max_length=65536, null=True),
        ),
    ]
